package com.backendvovoluisa.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

@Data
@DynamoDBTable(tableName = "userAccount")
public class UserAccount {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute
    private String userName;

    @DynamoDBAttribute
    private Long userPhone;

    @DynamoDBAttribute
    private Long userCpf;

    @DynamoDBAttribute
    private String userEndereco;

    @DynamoDBAttribute(attributeName = "userDataNascimento")
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate userDataNascimento;

    @DynamoDBAttribute
    private String userEmail;

    @DynamoDBAttribute(attributeName = "userDataCriacao")
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate userDataCriacao;

    public UserAccount() {
        
    }

    public UserAccount(String userId, String userName, Long userPhone, Long userCpf, String userEndereco, LocalDate userDataNascimento, String userEmail, LocalDate userDataCriacao) {
        this.userId = userId;
        this.userName = userName;
        this.userPhone = userPhone;
        this.userCpf = userCpf;
        this.userEndereco = userEndereco;
        this.userDataNascimento = userDataNascimento;
        this.userEmail = userEmail;
        this.userDataCriacao = userDataCriacao;
    }

    public static class LocalDateConverter implements DynamoDBTypeConverter<String, LocalDate> {
        private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        @Override
        public String convert(final LocalDate localDate) {
            return localDate.format(FORMATTER);
        }

        @Override
        public LocalDate unconvert(final String stringValue) {
            return LocalDate.parse(stringValue, FORMATTER);
        }
    }
}
